### ISSUE TITLE
Enable GitHub Discussion.

### ISSUE THREAD

**Issue by roke-julian-lockhart** [mattl/librefm#3]
My rationale is available at https://github.com/8go/matrix-commander/issues/68#issue-1237645245:

<blockQuote>

I want to ask questions, but am not certain of where to.

Consequently, enablement of https://docs.github.com/discussions is useful, because it allows questions to be asked without unnecessary triage and closure, and provides obvious demonstration of resolution:

![(Which this demonstrates.)](http://i0.wp.com/user-images.githubusercontent.com/8809849/155399653-5a061395-b1d3-4951-8a53-9b30875f596d.png) 

I am thankful for any consideration.

</blockQuote>

Specifically, I'd like to ask why `laconica_profile` at https://libre.fm/user-edit.php doesn't accept https://gnusocial.net/rokejulianlockhart (it silently deletes it from the profile after saving).

**Comment by mattl** [comment]
This is the wrong repo for the old project. See github.com/foocorp/gnu-fm
